#index:
#    path: /
#    controller: App\Controller\DefaultController::index
authentication_token:
    path: /authentication_token
    methods: ['POST']

refresh_token:
    path: /refresh_token
    controller: gesdinet.jwtrefreshtoken::refresh